# block some countries
[[redirects]]
  from = "/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["BY","FI","CU","IR","IQ","CI","LR","KP","SD","SY","ZW"]}
  headers = {Link = "<https://uniswap.nordicenergy.co>"}

# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
